crm/urls.py
from . import views
from django.urls import path, include, re_path
from django.contrib.auth import views as auth_views


app_name = 'crm'
urlpatterns = [
    path('', views.home, name='home'),
    re_path(r'^home/$', views.home, name='home'),
    path('student_list', views.student_list, name='student_list'),
    path('event_list', views.event_list, name='event_list'),
    path('club_list', views.club_list, name='club_list'),
    path('meal_list', views.meal_list, name='meal_list'),
    path('student/<int:pk>/edit/', views.student_edit, name='student_edit'),
    path('student/<int:pk>/delete/', views.student_delete, name='student_delete'),
    path('event/<int:pk>/edit/', views.event_edit, name='event_edit'),
    path('event/<int:pk>/delete/', views.event_delete, name='event_delete'),
    path('club/<int:pk>/edit/', views.club_edit, name='club_edit'),
    path('club/<int:pk>/delete/', views.club_delete, name='club_delete'),
    path('meal/<int:pk>/edit/', views.meal_edit, name='meal_edit'),
    path('meal/<int:pk>/delete/', views.meal_delete, name='meal_delete'),
    path('register/', views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('accounts/', include('django.contrib.auth.urls'))
]

mfscrm/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('crm.urls')),
]

crm/models.py
from django.db import models
from django.utils import timezone


#Define the model for the Customer table
class Student(models.Model):
    username = models.CharField(max_length=50)
    password = models.CharField(max_length=50)
    student_name = models.CharField(max_length=50)
    email = models.EmailField(max_length=100)
    phone = models.CharField(max_length=20)
    city = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    nu_id = models.CharField(max_length=100)
    role = models.CharField(max_length=100)

    def __str__ (self):
        return self.student_name

class Club(models.Model):
    club_name = models.CharField(max_length=100)
    club_category = models.CharField(max_length=100)
    club_description = models.TextField()
    created_date = models.DateTimeField(
        default=timezone.now)

    def __str__(self):
        return str(self.club_name)

class Event(models.Model):
    Club = models.ForeignKey(Club, on_delete=models.CASCADE, related_name='clubs')
    event_name = models.CharField(max_length=50)
    event_category = models.CharField(max_length=100)
    description = models.TextField()
    location = models.CharField(max_length=200)
    event_date = models.DateTimeField(default=timezone.now)
    def __str__(self):
        return str(self.event_name)

class Meal(models.Model):
    meal_name = models.CharField(max_length=200)
    meal_description = models.CharField(max_length=200)
    meal_drink = models.CharField(max_length=200)
    price = models.CharField(max_length=200)

crm/forms.py
from django import forms
from .models import Student, Event, Club, Meal


class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ('username', 'password', 'student_name', 'email', 'phone', 'city', 'state','nu_id','role')


class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = ( 'event_name', 'event_category', 'description', 'location', 'event_date')

class ClubForm(forms.ModelForm):
    class Meta:
        model = Club
        fields = ( 'club_name', 'club_category', 'club_description', 'created_date')

class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password', widget=forms.PasswordInput)
    class Meta:
        model = Student
        fields = ('username', 'student_name', 'email', 'nu_id', 'city', 'state', 'phone', 'role', 'password' )
    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']: raise forms.ValidationError('Passwords don\'t match.')
        return cd['password2']

class MealForm(forms.ModelForm):
    class Meta:
        model = Meal
        fields = ('meal_name', 'meal_description', 'meal_drink', 'price')

crm/views.py
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.admin.views.decorators import staff_member_required
from django.shortcuts import render, get_object_or_404, redirect
from .models import *
from .forms import *
from .forms import UserRegistrationForm
from .models import Student, Event, Club



now = timezone.now()

def register(request):
    if request.method == 'POST':
        student_form = UserRegistrationForm(request.POST)
        if student_form.is_valid():
            new_user = student_form.save(commit=False)

            new_user.save()
            return render(request, 'registration/register_done.html', {'new_user': new_user})
    else:
        student_form = UserRegistrationForm()
    return render(request, 'registration/register.html', {'student_form': student_form})


def home(request):
    return render(request, 'crm/home.html',
                  {'crm': home})



@staff_member_required
def student_list(request):
    student = Student.objects.filter()
    return render(request, 'crm/student_list.html',
                  {'students': student})

@staff_member_required
def student_edit(request, pk):
    student = get_object_or_404(Student, pk=pk)
    if request.method == "POST":
        # update
        form = StudentForm(request.POST, instance=student)
        if form.is_valid():
            student = form.save(commit=False)
            student.updated_date = timezone.now()
            student.save()
            student = Student.objects.filter()
            return render(request, 'crm/student_list.html',
                          {'students': student})
    else:
        # edit
        form = StudentForm(instance=student)
    return render(request, 'crm/student_edit.html', {'form': form})
@user_passes_test(lambda u: u.is_superuser)
def student_delete(request, pk):
    student = get_object_or_404(Student, pk=pk)
    student.delete()
    return redirect('crm:student_list')
@login_required
def event_list(request):
    event = Event.objects.filter()
    return render(request, 'crm/event_list.html',
                  {'events': event})

@staff_member_required
def event_edit(request, pk):
    event = get_object_or_404(Event, pk=pk)
    if request.method == "POST":
        # update
        form = EventForm(request.POST, instance=event)
        if form.is_valid():
            event = form.save(commit=False)
            event.updated_date = timezone.now()
            event.save()
            event = Event.objects.filter()
            return render(request, 'crm/event_list.html',
                          {'events': event})
    else:
        # edit
        form = EventForm(instance=event)
    return render(request, 'crm/event_edit.html', {'form': form})
@user_passes_test(lambda u: u.is_superuser)
def event_delete(request, pk):
    event = get_object_or_404(Event, pk=pk)
    event.delete()
    return redirect('crm:event_list')




@login_required
def club_list(request):
    club = Club.objects.filter()
    return render(request, 'crm/club_list.html',
                  {'clubs': club})

@staff_member_required
def club_edit(request, pk):
    club = get_object_or_404(Club, pk=pk)
    if request.method == "POST":
        # update
        form = ClubForm(request.POST, instance=club)
        if form.is_valid():
            club = form.save(commit=False)
            club.updated_date = timezone.now()
            club.save()
            club = Club.objects.filter()
            return render(request, 'crm/club_list.html',
                          {'clubs': club})
    else:
        # edit
        form = ClubForm(instance=club)
    return render(request, 'crm/club_edit.html', {'form': form})
@user_passes_test(lambda u: u.is_superuser)
def club_delete(request, pk):
    club = get_object_or_404(Club, pk=pk)
    club.delete()
    return redirect('crm:club_list')

@login_required
def meal_list(request):
    meal = Meal.objects.filter()
    return render(request, 'crm/meal_list.html',
                  {'meals': meal})


@staff_member_required
def meal_edit(request, pk):
    meal = get_object_or_404(Meal, pk=pk)
    if request.method == "POST":
        # update
        form = MealForm(request.POST, instance=meal)
        if form.is_valid():
            meal = form.save(commit=False)
            meal.updated_date = timezone.now()
            meal.save()
            meal = Meal.objects.filter()
            return render(request, 'crm/meal_list.html',
                          {'meals': meal})
    else:
        # edit
        form = MealForm(instance=meal)
    return render(request, 'crm/meal_edit.html', {'form': form})

@user_passes_test(lambda u: u.is_superuser)
def meal_delete(request, pk):
    meal = get_object_or_404(Meal, pk=pk)
    meal.delete()
    return redirect('crm:meal_list')

crm/templates/crm/base.html
<!-- New base page  -->
<!DOCTYPE html>
{% load static %}

<html lang="en">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="{% static 'css/w3.css' %}">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">
<!-- jQuery library -->
<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"></script>
<!-- Latest compiled JavaScript -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>

<div class="container-fluid">
    <div class="navbar-header">
        <a class="navbar-dark" href=""> Maverick Gram
        </a>

        <!-- Button to collapse Navbar Button -->
        <button type="button" class="navbar-toggle" data-toggle="collapse"
                data-target="#myNavbar" aria-controls="myNavbar">
            Toggle Navigation
        </button>


    </div>
<!-- not sure  --><!-- not sure  --><!-- not sure  --><!-- not sure  --><!-- not sure  --><!-- not sure  --><!-- not sure  --><!-- not sure  -->

     <!-- Dark background with white text --> <!-- Dark background with white text --> <!-- Dark background with white text --> <!-- Dark background with white text -->
     <nav class="navbar navbar-expand-md bg-dark navbar-light" id="myNavbar">
        <!--Display navigation options left-justified in navbar -->
        <ul class="navbar-nav mr-auto">
            <li class="navbar-brand"></li>

            <li class="nav-item active">
                <a href="{% url 'crm:home' %}" class="w3-bar-item w3-button w3-padding-large w3-hover-black"> <i class="fa fa-home w3-xxlarge"> </i><p>HOME</p> </a>
            </li>


            <li class="nav-item">
                <a href="{% url 'crm:event_list' %}" href="#events" class="w3-bar-item w3-button w3-padding-large w3-hover-black"> <i class="fa fa-newspaper-o w3-xxlarge"></i> <p>Events</p> </a>
            </li>

            <li class="nav-item">
                <a  href="{% url 'crm:club_list' %}" href="#clubs" class="w3-bar-item w3-button w3-padding-large w3-hover-black"> <i class="fa fa-users w3-xxlarge"></i> <p>Clubs</p> </a>
            </li>


            <li class="nav-item active">
                <a href="{% url 'crm:meal_list' %}" href="#meal" class="w3-bar-item w3-button w3-padding-large w3-hover-black"> <i class="fa fa-github-alt w3-xxlarge"></i> </i><p>Meals</p> </a>
            </li>

            <li class="nav-item active">
                <a href="{% url 'crm:student_list' %}" class="w3-bar-item w3-button w3-padding-large w3-hover-black"> <i class="fa fa-vcard w3-xxlarge"> </i><p>Students</p> </a>
            </li>

        </ul>

        <!--Display Login/Logout right-justified in navbar -->
        <ul class="nav navbar-nav ml-auto">
        <!--Display Register -->
            <li class="nav-item active">
                <a href="{% url 'crm:register' %}" class="w3-bar-item w3-button w3-padding-large w3-hover-black"> <i class="fa fa-pencil w3-xxlarge"></i> <p>Register</p> </a>
            </li>

            {% if user.is_authenticated %}
                <li class="nav-item active">
                    <a href="{% url 'logout' %}" class="w3-bar-item w3-button w3-padding-large w3-hover-black"> <i class="fa fa-sign-in w3-xxlarge"> </i><p>Logout</p> </a>
                </li>

            {% else %}
                <li class="nav-item active">
                    <a href="{% url 'login' %}" class="w3-bar-item w3-button w3-padding-large w3-hover-black"> <i class="fa fa-sign-in w3-xxlarge"> </i><p>Login</p> </a>
                </li>
            {% endif %}

        </ul>
    </nav>

</div>

<body id="app-layout">
<div class="row">
    <div class="col-md-8">
        {% block content %}
        {% endblock %}
    </div>
</div>
</div>
</body>

</html>

crm/templates/crm/club_list.html
<!DOCTYPE html>
<html lang="en">
{% extends 'crm/base.html' %}
{% block content %}

    <html>
    <head>
        <meta charset="UTF-8">
        <title>Maverick Food Services</title>
    </head>
    <body class="bodylist">

    <div class="container">
        <div class="panel panel-primary">
            <div class="panel-heading">Welcome!</div>
            <div class="panel-body">
                Here you will find the club you like!
            </div>
        </div>
    </div>
    <div class="row">
        <h2>Club Information</h2>
        <td>  <a href="http://127.0.0.1:8000/admin/crm/club/add/"><span
                class="btn btn-primary">Add Club</span></a></td>
    </div>
    <div>
        <table class="table table-striped table-bordered table-hover w-auto">
            <thead>
            <tr class="bg-info">
                <th>Club Name</th>
                <th>Club Category</th>
                <th>Club Description</th>
                <th>Created　Date</th>
                <th colspan="4">Actions</th>
            </tr>
            </thead>
            <tbody>

            {% for club in clubs %}
                <tr>
                    <td>{{ club.club_name }}</td>
                    <td>{{ club.club_category }}</td>
                    <td>{{ club.club_description }}</td>
                    <td>{{ club.created_date }}</td>
                    <td><a href="{% url 'crm:club_edit' pk=club.pk %}"
                           class="btn btn-warning">Edit</a>
                    <td><a href="{% url 'crm:club_delete' pk=club.pk %}"
                           onclick="return confirm('Are you sure you want to delete?')"
                           class="btn btn-danger">Delete</a>

                </tr>
            {% endfor %}
            </tbody>
        </table>

    </div>
    </body>
    </html>
{% endblock %}

</html>

crm/templates/crm/club_new.html
<!DOCTYPE html>
<html lang="en">
{% extends 'crm/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <h1>Add a New Club</h1>
    <form method="POST" class="product-form">{% csrf_token %}
         {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Save</button>
    </form>
{% endblock %}
</html>

crm/templates/crm/event_delete.html
<!DOCTYPE html>
<html lang="en">
{% block body_block %}
    <h1>Delete {{ event.name }}?</h1>
    <form method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Delete">
        <a href="{% url 'crm:home' pk=customer.cust_number %} ">Cancel</a>
    </form>
{% endblock %}

</html>

crm/templates/crm/event_edit.html
<!DOCTYPE html>
<html lang="en">
{% extends 'crm/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
        <style>
        body {background-color: beige;}
    </style>
    <h1>Edit Event</h1>
    <form method="POST" class="customer-form">{% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Update</button>
    </form>
{% endblock %}
</html>

crm/templates/crm/event_list.html
<!DOCTYPE html>
{% extends 'crm/base.html' %}
{% block content %}
    {% load humanize %}

    <head>
        <title>Maverick Food service</title>
    </head>
    <body class="bodylist">
    <div class="container">

        <div class="panel panel-primary">
            <div class="panel-heading">Welcome!</div>
            <div class="panel-body">
                Maverick Gram, new  events are hosted daily!
            </div>
        </div>

    </div>
    <div class="row">
        <h2>Event Information</h2>
        <td>  <a href="http://127.0.0.1:8000/admin/crm/event/add/"><span
                class="btn btn-primary">Add Event</span></a></td>
    </div>
    <div>
        <table class="table table-striped table-bordered table-hover w-auto">
            <thead>
            <tr class="bg-info">
                <th>Event Name</th>
                <th>Event Category (Club)</th>
                <th>Event Description</th>
                <th>Location</th>
                <th>Event Date</th>
                <th colspan="2">Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for event in events %}

                <tr>
                    <td>{{ event.event_name }}</td>
                    <td>{{ event.event_category }}</td>
                    <td>{{ event.description }}</td>
                    <td>{{ event.location }}</td>
                    <td>{{ event.event_date }}</td>
                    <td><a href="{% url 'crm:event_edit' pk=event.pk %}"
                           class="btn btn-warning">Edit</a>
                    </td>
                    <td><a href="{% url 'crm:event_delete' pk=event.pk %}"
                           onclick="return confirm('Are you sure you want to delete?')"
                           class="btn btn-danger">Delete</a>
                    </td>

                </tr>
            {% endfor %}
            </tbody>
        </table>

    </div>


    </body>
{% endblock %}

crm/templates/crm/event_new.html
<!DOCTYPE html>
<html lang="en">
{% extends 'crm/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <h1>Add a New event</h1>
    <form method="POST" class="product-form">{% csrf_token %}
         {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Save</button>
    </form>
    <td>
        <a href="http://127.0.0.1:8000/admin/crm/event/add/"><span class="btn btn-primary">Add event</span></a>
    </td>
{% endblock %}
</html>

crm/templates/crm/home.html
<!-- New home page 2.0 -->
<!DOCTYPE html>
<html lang="en">
{% extends 'crm/base.html' %}
{% load static %}

<!-- title  -->
{% block content %}

    {% if user.is_authenticated %}
        <div class="page-container">
            <h2 class="top-menu">Welcome {{ user.username }}</h2>
        </div>
    {% else %}
        <p></p>
    {% endif %}
    <div class="content container">

        <head>
        <title>CSS Template</title>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="crm/static/css/w3.css" />

        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Montserrat"
        />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
        />
        <style>
          body,
          h1,
          h2,
          h3,
          h4,
          h5,
          h6 {
            font-family: "Montserrat", sans-serif;
          }
          .w3-row-padding img {
            margin-bottom: 12px;
          }
          /* Set the width of the sidebar to 120px */
          .w3-sidebar {
            width: 120px;
            background: #222;
          }
          #main {
            margin-left: 120px;
          }
          /* Remove margins from "page content" on small screens */
          @media only screen and (max-width: 600px) {
            #main {
              margin-left: 0;
            }
          }
        </style>
    </head>

        <body class="w3-black">
        <div class="w3-padding-large" id="main">
          <header class="w3-container w3-padding-32 w3-center w3-black" id="home">
            <h1 class="w3-jumbo">
              <span class="w3-hide-small">Maverick Gram ©</span>
            </h1>
            <p>
              Maverick Gram, we are here to make your campus life little easier.
            </p>
            <img src="{% static "images/Mavericks.jpeg" %}" class="w3-image" width="800" height="1000" alt="Mavericks">
          </header>
<!-- Event  -->
          <div class="w3-padding-64 w3-content" id="events">
            <h2 class="w3-text-light-grey">Events</h2>
            <hr style="width: 200px" class="w3-opacity" />
              <!-- not sure  --><!-- not sure  --><!-- not sure  --><!-- not sure  --><!-- not sure  --><!-- not sure  -->
            <div class="card-body">
                 <p><a class="btn btn-info" href="{% url 'crm:event_list' %}"
                      role="button">View details &raquo;</a></p>
            </div>

            <div class="w3-row-padding" style="margin: 0 -16px">
              <div class="w3-half">
            <img src="{% static "images/bowling.jpeg" %}" class="w3-image" style="width: 100%"  alt="bowling_photo">
            <img src="{% static "images/dodgeball.jpeg" %}" class="w3-image" style="width: 100%"alt="dodgeball_photo">
          </div>
              <div class="w3-half">
                <img src="{% static "images/movie.jpeg" %}" style="width: 100%" alt="movie_photo">
                <img src="{% static "images/basketball.png" %}" style="width: 100%" alt="basketball_photo">
                <img src="{% static "images/trivia.png" %}" style="width: 100%" alt="trivia_photo">
              </div>
            </div>
          </div>
<!-- club  -->
          <div class="w3-padding-64 w3-content w3-text-grey" id="clubs">
            <h2 class="w3-text-light-grey">Clubs</h2>
            <hr style="width: 200px" class="w3-opacity" />

            <div class="card-body">
                 <p><a class="btn btn-info" href="{% url 'crm:club_list' %}"
                      role="button">View details &raquo;</a></p>
            </div>

            <div class="w3-row-padding" style="margin: 0 -16px">
              <div class="w3-half">
                <img src="{% static "images/arthistory.png" %}" style="width: 100%" alt="arthistory">
                <img src="{% static "images/bookclub.jpeg" %}" style="width: 100%" alt="bookclub">
                <img src="{% static "images/chess.jpeg" %}" style="width: 100%" alt="chess">
              </div>

              <div class="w3-half">
                <img src="{% static "images/math.jpeg" %}" style="width: 100%" alt="math">
                <img src="{% static "images/photo.jpeg" %}" style="width: 100%" alt="photo">
                <img src="{% static "images/speech.jpeg" %}" style="width: 100%" alt="speech">
                <img src="{% static "images/Sculpture.jpeg" %}" style="width: 100%" alt="Sculpture">
              </div>
            </div>
          </div>

<!-- meals -->
          <div class="w3-padding-64 w3-content" id="meal">
            <h2 class="w3-text-light-grey">Meals</h2>
            <hr style="width: 200px" class="w3-opacity" />
            <div class="card-body">
                 <p><a class="btn btn-info" href="{% url 'crm:meal_list' %}"
                      role="button">View details &raquo;</a></p>
            </div>
            <div class="w3-row-padding" style="margin: 0 -16px">
              <div class="w3-half">
                <img src="{% static "images/1.jpeg" %}" class="w3-image" style="width: 100%"  alt="food_1_photo">
                <img src="{% static "images/2.jpeg" %}" class="w3-image" style="width: 100%"alt="food_2_photo">
                <img src="{% static "images/6.jpeg" %}" style="width: 100%" alt="food_6_photo">
              </div>
              <div class="w3-half">
                <img src="{% static "images/3.jpeg" %}" style="width: 100%" alt="food_3_photo">
                <img src="{% static "images/4.jpeg" %}" style="width: 100%" alt="food_4_photo">
                <img src="{% static "images/5.jpeg" %}" style="width: 100%" alt="food_5_photo">
              </div>
            </div>
          </div>

          <div class="w3-content w3-justify w3-text-grey w3-padding-64" id="about">
            <h2 class="w3-text-light-grey">Who are we?</h2>
            <hr style="width: 200px" class="w3-opacity" />
            <img src="{% static "images/bull.png" %}" class="w3-left w3-circle w3-margin-right" style="width: 80px" alt="Avatar">
            <p><span class="w3-large w3-margin-right">Maverick Gram©</span></p>
            <p>We design your website</p>
            <br />
            <p>
              MAVERICK GRAM application allowing all featured clubs, host to post
              announcements, club events and news on this one single platform which
              all students would have the access to. This program allows all users
              to see what's going on campus without having to search for each school
              related events individually on social media.
            </p>
          </div>
          <!-- Footer -->
          <footer class="w3-content w3-padding-64 w3-text-grey w3-xlarge">
            <i class="fa fa-facebook-official w3-hover-opacity"></i>
            <i class="fa fa-instagram w3-hover-opacity"></i>
            <i class="fa fa-snapchat w3-hover-opacity"></i>
            <i class="fa fa-pinterest-p w3-hover-opacity"></i>
            <i class="fa fa-twitter w3-hover-opacity"></i>
            <i class="fa fa-linkedin w3-hover-opacity"></i>
            <p class="w3-medium">Maverick Gram 2022©</p>
          </footer>
        </div>
    </body>
    </div>
{% endblock %}
</html>

crm/templates/crm/meal_list.html
<!DOCTYPE html>
{% extends 'crm/base.html' %}
{% block content %}
    {% load humanize %}

    <head>
        <title>Maverick Food service</title>
    </head>
    <body class="bodylist">
    <div class="container">

        <div class="panel panel-primary">
            <div class="panel-heading">Welcome!</div>
            <div class="panel-body">
                Check out new meals at the Mav Cafe every day!
            </div>
        </div>

    </div>
    <div class="row">
        <h2>Meal Information</h2>
        <td>  <a href="http://127.0.0.1:8000/admin/crm/meal/add/"><span
                class="btn btn-primary">Add Meals</span></a></td>
    </div>
    <div>
        <table class="table table-striped table-bordered table-hover w-auto">
            <thead>
            <tr class="bg-info">
                <th>Meal Name</th>
                <th>Meal Description</th>
                <th>Drink Choices</th>
                <th>Meal Price</th>
                <th colspan="2">Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for meal in meals %}
                <tr>
                    <td>{{ meal.meal_name }}</td>
                    <td>{{ meal.meal_description }}</td>
                    <td>{{ meal.meal_drink }}</td>
                    <td>{{ meal.price }}</td>
                    <td><a href="{% url 'crm:meal_edit' pk=meal.pk %}"
                           class="btn btn-warning">Edit</a>
                    </td>
                    <td><a href="{% url 'crm:meal_delete' pk=meal.pk %}"
                           onclick="return confirm('Are you sure you want to delete?')"
                           class="btn btn-danger">Delete</a>
                    </td>


                </tr>
            {% endfor %}
            </tbody>
        </table>

    </div>


    </body>
{% endblock %}

crm/templates/crm/student_list.html
<!DOCTYPE html>
<html lang="en">
{% extends 'crm/base.html' %}
{% block content %}
    <html>
    <head>
        <meta charset="UTF-8">
        <title>Maverick Gram</title>
    </head>
    <body class="bodylist">

    <div class="container">
        <div class="panel panel-primary">
            <div class="panel-heading">Hello!</div>
            <div class="panel-body">
                Welcome to Maverick Gram!
            </div>
        </div>
    </div>
    <div class="row">
        <h2>Student Information</h2>
        <td><a href="http://127.0.0.1:8000/admin/crm/student/add/"><span class="btn btn-primary">Add Student</span></a>
        </td>
    </div>
    <div>
        <table class="table table-striped table-bordered table-hover w-auto">
            <thead>
            <tr class="bg-info">
                <th>Username</th>
                <th>Password</th>
                <th>Student Name</th>
                <th>Email</th>
                <th>Phone</th>
                <th>City</th>
                <th>State</th>
                <th>NUID</th>
                <th>Role</th>

                <th colspan="4">Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for student in students %}
                <tr>
                    <td>{{ student.username }}</td>
                    <td>{{ student.password }}</td>
                    <td>{{ student.student_name }}</td>
                    <td>{{ student.email }}</td>
                    <td>{{ student.phone }}</td>
                    <td>{{ student.city }}</td>
                    <td>{{ student.state }}</td>
                    <td>{{ student.nu_id }}</td>
                    <td>{{ student.role }}</td>
                    <td><a href="{% url 'crm:student_edit' pk=student.pk %}"
                           class="btn btn-warning">Edit</a></td>
                    <td><a href="{% url 'crm:student_delete' pk=student.pk %}"
                           onclick="return confirm('Are you sure you want to delete?')"
                           class="btn btn-danger">Delete</a>
                    </td>

                </tr>
            {% endfor %}
            </tbody>
        </table>

    </div>
    </body>
    </html>
{% endblock %}

</html>